version: '3'

services:
  database:
    container_name: database
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/dump:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php-fpm:
    container_name: php-fpm
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
      - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE}
      - PHP_XDEBUG_CLIENT_PORT=${PHP_XDEBUG_CLIENT_PORT}
      - PHP_XDEBUG_CLIENT_HOST=${PHP_XDEBUG_CLIENT_HOST}
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./app:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    volumes:
      - ./app:/var/www
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always


